apache/cordova-js

- src/browser/confighelper.js
This implements confighelper module for config.xml preferences retrieval at runtime for browser platform. JIRA issue: https://issues.apache.org/jira/browse/CB-8223
> CB-8223 Adds configparser module for exposing config.xml in the Browser platform

- src/cordova.js
- src/cordova_b.js
Verify that window.cordova does not already exist and throw error if it does.
Tested on ios/android/wp8.
> CB-7992 prohibit multiple cordova includes

- src/legacy-exec/windows/platform.js
Fixed this change for cordova-js as well as in cordova-windows.
> CB-9057: Updated cordova.js for Windows to refer to base.js instead of winjs.js

- tasks/lib/require-tr.js
This fixes cordova-lib tests failures in Windows environment. See [CB-9137](https://issues.apache.org/jira/browse/CB-9137).
> CB-9137 Fixes cordova-lib tests failures

- .travis.yml
- appveyor.yml
- package.json
- tasks/lib/test-jsdom.js
This PR fixes tests on AppVeyor, broken by updated NodeJS on CI machines as described in [CB-9370](https://issues.apache.org/jira/browse/CB-9370). It also adds build matrix that includes node 0.10 and 0.12 for both Travis and AppVeyor.
> CB-9370 Fixes failing tests on Node 0.12 due to stale dependency

- package.json
- tasks/lib/test-jsdom.js
This resolves build failures on AppVeyor (https://ci.appveyor.com/project/Humbedooh/cordova-lib/build/1.0.911).
See [CB-9370](https://issues.apache.org/jira/browse/CB-9370) for details.
> CB-9370 Switches to another jsdom dependency to avoid package installation issues

- src/scripts/require.js
- test/test.require.js
Using relative paths in calls to `require` failed.
The single-character patch caused me to chuckle.
Added a test for this as well.
> CB-13163: fix using relative paths in calls to require.

- package.json
So that we can close https://issues.apache.org/jira/browse/CB-8990
> CB-8990: bump nodejs requirement to 4.0.0+

- appveyor.yml
- package.json
All
- Mark 4.2.4-dev in package.json
- Update appveyor.yml & .travis.yml to use npm@5 as a QUICK FIX WORKAROUND for Node.js 4
NOTES:
- It is **not** acceptable to drop Node.js 4 before next major release.
- Use of non-master branch in cordova-js seems to cause some problems with cordova-coho. I hope to investigate and resolve this one in the near future. Until then I would like to avoid the need for non-master branch for patches, which implies:
- avoid major version bump inn this repo unless absolutely necessary
- need to maintain Node.js support until we resolve the issue with cordova-coho
These changes were originally part of WIP PR #151 which passes CI, will check CI results of this PR.
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- …
> Start 4.2.4 dev & fix CI for Node.js 4

- package.json
- tasks/lib/test-browser.js
THANKS for GUIDANCE:
https://medium.freecodecamp.org/getting-off-the-ground-with-expressjs-89ada7ef4e59
All
Use `express` to fix btest
THANKS for GUIDANCE: <https://medium.freecodecamp.org/getting-off-the-ground-with-expressjs-89ada7ef4e59>
`grunt btest` now starts a local server; opening <http://localhost:3000> in a browser shows passing test suite
This change seems to pass CI as part of WIP PR #151.
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
> Fix btest by using express (instead of connect, etc.)

- .eslintignore
- Gruntfile.js
- package.json
- tasks/compile.js
- tasks/lib/bundle.js
- tasks/lib/collect-files.js
- tasks/lib/compute-commit-id.js
- tasks/lib/copy-props.js
- tasks/lib/get-module-id.js
- tasks/lib/packager.js
- tasks/lib/strip-header.js
- tasks/lib/write-contents.js
- tasks/lib/write-module.js
- tasks/lib/write-script.js
Prior to this change, files under `tasks/` had not been linted. 3rd party code under `tasks/vendor` is still excluded from linting.
> Lint (almost) all JS files

- src/scripts/require.js
- test/test.require.js
One of the CommonJS tests in #195 exposed a defect in Cordova's module system:
When trying to define a module with a name that also is a property of `Object.prototype`, an exception would occur.
Use `Object.prototype.hasOwnProperty.call(modules, id)` to check if a module has already been defined, instead of the previously used `modules[id]`.
The changes make the previously failing test pass.
> Fix adopted CommonJS test `hasOwnProperty`

- src/common/argscheck.js
- test/test.argscheck.js
Some parameter formats were not parsed correctly in `argscheck.checkArgs`. This would lead to faulty error messages.
Tweaked the RegExes in `extractParamName` to consume all white space around the tokens of interest.
The recognition is still not perfect (e.g. parameters with defaults). For that, one would have to employ an actual parser. But that's a bit over the top here.
Added regression test
> Fix parsing of some parameter formats in argscheck.checkArgs

- .travis.yml
- appveyor.yml
- package.json
- test/build.js
Until now, the tests required the platforms used during tests (`cordova-android` & `cordova-ios`) to be manually checked out to the parent folder of this repository.
This PR requires the platforms used during tests as `devDependencies` and changes the test build and CI configurations accordingly.
> Add platforms used during tests as devDependencies

- build-tools/bundle.js
- build-tools/common.js
- build-tools/modules.js
- build-tools/scripts.js
- test/build.js
In #205 I took great care to preserve the _exact_ format of the built
JS code, so the build refactoring could be verified by diffing the
build output. However, some of the existing formatting is sub-optimal
so this commit optimizes it a little.
Most notably, this commit will change file path comments to be relative
paths, not absolute ones. An example for this:
```diff
-// file: /home/raphinesse/code/cordova-android/cordova-js-src/exec.js
+// file: ../cordova-android/cordova-js-src/exec.js
```
I diffed the build artifacts and verified that the diff was as expected. Except for the test build, the diff only consists of whitespace and comments.
> Make built JS output a bit prettier

- karma.conf.js
- package.json
- test/build.js
We haven't had code coverage for our client JS tests for some time. With this PR, running the tests also creates a code coverage report.
Since our tests are run by `karma`, we use `karma-coverage` to create the code coverage report. However, since we are using a custom module system that is somewhere between RequireJS and CommonJS, we have to do the test code instrumenting ourselves. We use the Istanbul JS API for that. To be as compatible with `karma-coverage` as possible, we do not add `istanbul` to our `devDependencies` but instead, when requiring it, we rely on getting the version of `istanbul` that `karma-coverage` depends on.
> Collect & report test coverage for our browser code

- build-tools/test-build.js
- package.json
- src/.eslintrc.yml
- src/common/base64.js
- src/common/channel.js
- src/common/modulemapper.js
- src/common/pluginloader.js
- src/common/utils.js
- src/cordova.js
- test/.eslintrc.yml
- test/android/test.exec.js
- test/ios/test.exec.js
- test/test-platform-modules/.eslintrc.yml
- test/test-platform-modules/exec.js
- test/test.base64.js
- test/test.pluginloader.js
- test/test.urlutil.js
- test/test.utils.js
- Add proper ESLint configuration
- Fix ESLint violations instead of ignoring them
- Remove unused function
- Remove node-only code
- This was previously required for being able to run the tests on Node.js. But since we now run them in an actual browser, this isn't required anymore.
- Check that we only use ES5 in our browser code
- Required for Android 4.4 (cordova-android) and IE 11 (cordova-windows) support
> ESLint cleanup

- .eslintrc.yml
- Gruntfile.js
- src/common/init.js
- src/common/utils.js
- src/scripts/require.js
- test/test.builder.js
- test/test.require.js
- test/test.urlutil.js
- test/test.utils.js
- Reduce exceptions from our ESLint base rule set.
- Do not throw literals
Conservatively, this should go into a major release because the type of thrown object changes for `require`/`define`.
> Re-enable ESLint rules

- src/common/init.js
`window.navigator` is a read-only property. Thus the current code for replacing it cannot succeed in a [spec][1] compliant browser. In strict mode the attempt will throw an error. In sloppy mode, the one Cordova is currently running in, the attempt is silently ignored.
Since apps seem to have been doing OK with the original `Navigator` object we should just remove the code trying to replace it.
[1]: https://html.spec.whatwg.org/multipage/window-object.html#the-window-object
> Do not try to replace window.navigator

- package.json
As it had erroneously been added to `dependencies` instead.
> fix: move eslint-plugin-es5 to devDependencies

- .travis.yml
- appveyor.yml
- package.json
- Drop unsupported Node.js versions
- Bump minimum supported Node.js to >=10
- Remove Node.js 8 from CI test workflow
- `npm t`
> breaking: bump minimum node support >=10

- .npmignore
- package.json
- Cleanup cordova-js package
- Updated Package Properties:
- `author`: change to `Apache Software Foundation`
- `repository`: use shorten format
- `bugs`: use GitHub URL and shorten format
- `contributors`: move previous author information to contributors list
- Added `.npmignore` file to shrink bundled package.
- `npm t`
> chore(npm): package cleanup

- .npmignore
- build-tools/build.js
- build-tools/test-build.js
- package-lock.json
- package.json
Bring all dependencies up to date (latest).
Requires #223 to be merged first
**Dev Dependencies**
* `@cordova/eslint-config@^3.0.0`
* `cordova-android@^8.1.0`
* `cordova-ios@^5.1.1`
* `eslint-plugin-es5@^1.5.0`
* `grunt@^1.1.0`
* `jasmine-core@^3.5.0`
* `karma@^4.4.1`
* `karma-chrome-launcher@^3.1.0`
* `karma-coverage@^2.0.1`
* `karma-jasmine@^3.1.1`
* `puppeteer@^2.1.1`
**Dependencies**
* `execa@^4.0.0`
* `fs-extra@^9.0.0`
* `globby@^11.0.0`
Applied `execa` fix.
- `npm t`
> breaking(npm): bump dependencies

- .github/workflows/ci.yml
* Test with Node 14.x
* Added Node 14.x CI all workflow configurations.
See https://github.com/apache/cordova/issues/223 for more details.
* No local testing required.
* Use CI service test results
> ci: add node-14.x to workflow

- build-tools/build-id.js
- build-tools/bundle.js
Currently the SHA of the commit pointed to by `HEAD` is included in the built `cordova.js` file to identify the version of `cordova-js` used to build it. If platforms depend on `cordova-js` in the future (see #169 & #229), they will most likely depend on published packages. Consequently there will be no `cordova-js` repo to get aforementioned information from.
To make things worse, git will automatically use a repo in any parent dir. So if you have `cordova-android/` containing `.git/` and `node_modules/cordova-js/`, the old implementation would use the HEAD of `cordova-android/.git/` to describe `cordova-js`.
Thus, we now include the version from `package.json` instead in that case.
- uses `git describe` instead of `git rev-parse HEAD` if in a `cordova-js` repo
- fall back to version …
> build: improve cordova-js version ID in built file

- README.md
- build-tools/build.js
- build-tools/cli.js
- index.js
- package.json
This resolves #169
This PR
- adds an option to the build-tools that can be used to infer all necessary information for a build from a platform's `package.json`
- exports the JS API of the cordova-js build-tools so it can be used by platforms (for special use cases, e.g. test builds)
- adds a very basic CLI that can be used by platforms instead of the JS API to build cordova.js (e.g. for running from a npm `prepare` hook)
Manually implemented the new build in electron: https://github.com/raphinesse/cordova-electron/commit/131311ed593b9395dd170b48a5837e1827df077d
> feat: export build-tools JS API & add CLI

- package-lock.json
- package.json
This PR:
* Removes a high severity vulnerability found in `cordova-android`, one of the `devDependency` of this package for testing.
* Rebuilt `package-lock.json`
- `npm t`
> chore(npm): bump dev dependency cordova-android@9.1.0

- build-tools/common.js
- build-tools/test-build.js
- package-lock.json
- package.json
n/a
Replace fs-extra for node internal fs package.
- Remove fs-extra package
- Use `node:fs` and `node:fs/promises`
- Bump node engine requirement to `>=16.20.2`
- `npm t`
> dep!: drop fs-extra for internal node:fs & bump node engine >=16.20.2

- .github/workflows/ci.yml
n/a
Do no fail on error with codecov
set `fail_ci_if_error` to `false`
n/a
> ci: codecov - do not fail on error

- build-tools/build-id.js
- build-tools/build.js
- build-tools/cli.js
- build-tools/common.js
- build-tools/modules.js
- build-tools/scripts.js
- build-tools/test-build.js
- package-lock.json
- package.json
- test/android/test.exec.js
Since we can't adopt the latest versions of execa and globby due to ESM, and we use them for very specific purposes here, replace them with built-ins where possible (and use fast-glob where not possible).
- Replace the single `execa` call with `child_process.spawnSync`, since we know that we're invoking `git` rather than a shell script
- Replace the one spot that used `globby` with `fast-glob`
- On versions of node with `fs.globSync`, use that instead of `fast-glob`
- Fix a warning in a Jasmine test about `done` getting called with arguments
- Update testing dependencies to latest versions
- Confirmed that the contents of the cordova.js file are the same before and after these changes (some extra spaces removed, but no code changes)
- Confirmed that all unit tests run and pass
> refactor: update and simplify some dependencies

- .github/workflows/ci.yml
* Add Node 22 to CI
* Don't run `push` events on Dependabot PRs because it can break things
* Add CodeQL scanning
> chore(ci): Add Node 22 to CI and fix dependabot PRs

- build-tools/common.js
Should have added Node 22 to CI _before_ doing the `fs.globSync` change 🤦🏼‍♂️ 
Windows
So `fs.glob` returns paths using the system path separator, while `fast-glob` and `globby` always return POSIX-style paths. Since we use this value for module IDs (i.e., `cordova.require('some/module/path')`) we need to ensure the IDs use POSIX-style separators.
NodeJS apparently still doesn't have an API to fix this beyond just doing string replacements.
Force module IDs to always use POSIX-style path separators.
Ran tests in CI with logging to reproduce and fix the bug.
> fix(glob): fs.glob uses native path separator which broke module IDs

- src/common/pluginloader.js
Because `indexOf` returns -1 in the case of no match, and a subtraction of string lengths can also potentially result in -1, we want to make sure the index is **not** -1 before we try to substring with it.
> fix: Fix potential edge case in cordova.js detection

- .github/workflows/ci.yml
- .github/workflows/release-audit.yml
- .ratignore
- licence_checker.yml
all
We want to ensure licence compliance at PR time.
* Add the licence checking action workflow
* Fix the dependabot workaround to actually work
Ran in CI
> chore(ci): Add licence checker workflow

- .github/workflows/ci.yml
- karma.conf.js
- package-lock.json
All
* Fix karma tests failing in GHA CI
* Add node 24 to CI matrix
* Update dependencies to resolve security audit warnings
On GHA runners, headless Chrome needs to run with the sandbox disabled due to kernel security things. We were already doing this previously for Travis.
Test pass locally.
> chore: CI fixes & deps updates
