src/cordova.js
src/cordova_b.js

NO_RESULT status was resolved as failure.

Fixed callbackFromNative method

---

.travis.yml
appveyor.yml

Jira issue: https://issues.apache.org/jira/browse/CB-8300

CB-8300 Added CI configuration files

---

src/cordova.js
src/cordova_b.js

Bringing back good old CB-7992 and #104

check the window.cordova object a little more strictly

---

src/legacy-exec/windows/platform.js

[Jira issue](https://issues.apache.org/jira/browse/CB-10558)

CB-10558 Update cordova-js according to windows8 deprecation

---

src/common/utils.js

See details in [CB-11522](https://issues.apache.org/jira/browse/CB-11522?focusedCommentId=15469653&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15469653)

CB-11522 [windows] Make cordova-js clone handle 'unknown' type

---

.travis.yml
Gruntfile.js
RELEASENOTES.md
package.json

All
- remove grunt jshint artifacts not needed (resolves some of the npm audit warnings)
- `.travis.yml` add spacing
- Update version & `RELEASENOTES.md` for release `4.2.3`
CI
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~

Finish version 4.2.3

---

package.json

All
Resolve existing npm audit issues:
- remove open & other devDepenencies for broken btest
- update jasmine-node@^1.14.6
These changes are part of WIP PR #151 which passes AppVeyor CI & Travis CI.
Note that AppVeyor CI is expected to be flaky in this PR. This should be fixed by removing clone of old, unsupported Cordova platforms.
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~

CB-14145 resolve npm audit issues in package.json

---

src/cordova.js

All
See title - rebase PR #118 & rework the JavaScript change
-

CB-9366 Log error.stack (as it helps with diagnosing the source of the error)

---

package.json

All
Followup to btest fix in PR #160: export npm script in package.json
`npm run btest` works as intended

CB-14155 fix btest part 2: export npm script

---

test/android/test.exec.js
test/ios/test.exec.js
test/test.argscheck.js
test/test.builder.js
test/test.channel.js
test/test.modulemapper.js
test/test.pluginloader.js
test/test.require.js
test/test.urlutil.js
test/test.utils.js

from #140 (with some modifications)

add test labels (GH-140)

---

Gruntfile.js
package.json
tasks/test.js

related to removed browserify functionality

additional btest cleanup

---

test/test.argscheck.js
test/test.base64.js
test/test.channel.js
test/test.utils.js

Add test labels from #140 that were missed in #172.

Add test labels from #140 that were missed in #172

---

Gruntfile.js
package.json

none
Add Support to Build for Electron
- Added Electron path to package.json
- Added Electron compile to Gruntfile.js
- `npm t`

Add Electron Support

---

appveyor.yml

Remove obsolete stuff from AppVeyor config

---

test/test.require.js

Some minor cleanup of the require/define tests.
See commits.

Minor cleanup of require/define tests

---

src/common/argscheck.js

Described behavior extracted from the current code. I am certain that I got it all covered.

Document argscheck

---

package.json

Target next major version 6.0.0

---

README.md

doc(README): update

---

package.json

Related to https://github.com/apache/cordova/issues/55

fix(pkg): make `npm home` resolve to repo readme

---

README.md

Just some very minor docs improvements

docs: some minor improvements

---

package.json

none
Prepare to merge in some breaking changes.
Bump version to 7.0.0-dev

feat: bump version 7.0.0-dev

---

.eslintrc.yml
package-lock.json
package.json

none
Use the latest `@cordova/eslint-config`
* bump `@cordova/eslint-config` to `^4.0.0`
* package-lock.js uses v2
* Applied custom rule to exclude no-var for all code since all code is runned in browser.

dep(npm): bump @cordova/eslint-config@^4.0.0 w/ custom rule

---

package-lock.json

none
rebuild package-lock to close dependabot PRs & with version 2
rebuilt package-lock.json
n/a

chore(npm): rebuild package-lock v2

---

.github/workflows/ci.yml

n/a
Update Codecov
- Run on success
- Add better run naming
n/a

ci: update codecov w/ name and run on success

---

.github/workflows/ci.yml

n/a
Update CI Workflow
- Use macOS-15
- Update Node Support Test Range - 20.x, 22.x, 24.x
- Pin codecov-action to git commit hash ID
- Fix license header formatting
n/a

ci: various cleanup & improvements
